import { and, asc, desc, eq, inArray, sql } from "drizzle-orm";
import {
  reports as reportsTable,
  inspections as inspectionsTable,
  projects as projectsTable,
  findings as findingsTable,
  observations as observationsTable,
  correctiveActions as correctiveActionsTable,
  evidence as evidenceTable,
  auditEvents,
  outboxEvents,
} from "../db/schema.js";
import type { DrizzleDB } from "../db/client.js";
import type { Report, ReportFormat, ReportStatus, DomainEventType } from "@netram/types";

export interface ReportRow {
  id: string;
  inspectionId: string;
  format: ReportFormat;
  status: ReportStatus;
  requestedBy: string | null;
  requestedAt: Date;
  generatedBy: string | null;
  generatedAt: Date | null;
  error: string | null;
  finalizedBy: string | null;
  finalizedAt: Date | null;
  createdAt: Date;
  updatedAt: Date;
  inspectionType: string;
  inspectionStatus: string;
  projectCode: string | null;
  projectName: string | null;
  districtId: string | null;
}

export function toReport(row: ReportRow): Report {
  return {
    id: row.id,
    inspectionId: row.inspectionId,
    format: row.format,
    status: row.status,
    inspectionType: row.inspectionType,
    inspectionStatus: row.inspectionStatus,
    projectCode: row.projectCode,
    projectName: row.projectName,
    districtId: row.districtId,
    requestedBy: row.requestedBy,
    requestedAt: row.requestedAt.toISOString(),
    generatedBy: row.generatedBy,
    generatedAt: row.generatedAt ? row.generatedAt.toISOString() : null,
    error: row.error,
    finalizedBy: row.finalizedBy,
    finalizedAt: row.finalizedAt ? row.finalizedAt.toISOString() : null,
    createdAt: row.createdAt.toISOString(),
    updatedAt: row.updatedAt.toISOString(),
  };
}

export interface ReportWriteContext {
  actorUserId: string | null;
  requestId: string | null;
  ipAddress: string | null;
}

export interface CreateReportWrite extends ReportWriteContext {
  id: string;
  inspectionId: string;
  format: ReportFormat;
}

export interface GenerateReportWrite extends ReportWriteContext {
  reportId: string;
  generatedBy: string | null;
  artifact: Record<string, unknown>;
  eventType: DomainEventType;
}

export interface FailReportWrite extends ReportWriteContext {
  reportId: string;
  errorMessage: string;
}

export interface FinalizeReportWrite extends ReportWriteContext {
  reportId: string;
  finalizedBy: string;
}

export interface ReportListFilter {
  page: number;
  pageSize: number;
  inspectionId?: string;
  status?: ReportStatus;
  jurisdictionIds?: string[];
}

export interface ReportSnapshotInspection {
  id: string;
  type: string;
  status: string;
  projectCode: string | null;
  projectName: string | null;
  districtId: string | null;
  scheduledStart: string | null;
  startedAt: string | null;
  submittedAt: string | null;
  createdAt: string;
}

export interface ReportSnapshotFinding {
  id: string;
  severity: string;
  description: string;
  remediation: string | null;
  status: string;
  createdAt: string;
}

export interface ReportSnapshotObservation {
  id: string;
  userId: string;
  text: string;
  createdAt: string;
}

export interface ReportSnapshotCorrectiveAction {
  id: string;
  findingId: string;
  status: string;
  deadline: string | null;
  createdAt: string;
}

export interface ReportSnapshotEvidence {
  id: string;
  evidenceType: string;
  fileName: string | null;
  uploadState: string;
  integrityState: string;
  capturedAt: string;
}

export interface ReportSnapshot {
  inspectionId: string;
  inspection: ReportSnapshotInspection;
  findings: ReportSnapshotFinding[];
  observations: ReportSnapshotObservation[];
  correctiveActions: ReportSnapshotCorrectiveAction[];
  evidence: ReportSnapshotEvidence[];
}

/**
 * Persistence for derived inspection reports (§34). Reports are per-inspection
 * artifacts generated by the report worker over authoritative records.
 */
export class ReportRepository {
  constructor(private db: DrizzleDB) {}

  private baseJoin() {
    return this.db
      .select({
        report: reportsTable,
        inspectionType: inspectionsTable.type,
        inspectionStatus: inspectionsTable.status,
        projectCode: projectsTable.code,
        projectName: projectsTable.name,
        districtId: projectsTable.districtId,
      })
      .from(reportsTable)
      .innerJoin(inspectionsTable, eq(reportsTable.inspectionId, inspectionsTable.id))
      .innerJoin(projectsTable, eq(inspectionsTable.projectId, projectsTable.id));
  }

  async list(filter: ReportListFilter): Promise<{ items: Report[]; total: number }> {
    const conditions: ReturnType<typeof eq>[] = [];
    if (filter.inspectionId) conditions.push(eq(reportsTable.inspectionId, filter.inspectionId));
    if (filter.status) conditions.push(eq(reportsTable.status, filter.status));
    const where = and(...conditions);

    const scope = filter.jurisdictionIds?.length
      ? inArray(projectsTable.districtId, filter.jurisdictionIds)
      : undefined;
    const scoped = and(where, scope);

    const [rows, count] = await Promise.all([
      this.baseJoin()
        .where(scoped)
        .orderBy(desc(reportsTable.requestedAt), desc(reportsTable.createdAt))
        .limit(filter.pageSize)
        .offset((filter.page - 1) * filter.pageSize),
      this.db
        .select({ count: sql<number>`count(*)::int` })
        .from(reportsTable)
        .innerJoin(inspectionsTable, eq(reportsTable.inspectionId, inspectionsTable.id))
        .innerJoin(projectsTable, eq(inspectionsTable.projectId, projectsTable.id))
        .where(scoped),
    ]);

    const items = rows.map((r) =>
      toReport({
        ...r.report,
        inspectionType: r.inspectionType,
        inspectionStatus: r.inspectionStatus,
        projectCode: r.projectCode,
        projectName: r.projectName,
        districtId: r.districtId,
      } as unknown as ReportRow),
    );
    return { items, total: count[0]?.count ?? 0 };
  }

  async findById(id: string): Promise<Report | null> {
    const rows = await this.baseJoin().where(eq(reportsTable.id, id)).limit(1);
    if (!rows[0]) return null;
    const r = rows[0];
    return toReport({
      ...r.report,
      inspectionType: r.inspectionType,
      inspectionStatus: r.inspectionStatus,
      projectCode: r.projectCode,
      projectName: r.projectName,
      districtId: r.districtId,
    } as unknown as ReportRow);
  }

  async create(cmd: CreateReportWrite): Promise<Report> {
    await this.db.transaction(async (tx) => {
      await tx.insert(reportsTable).values({
        id: cmd.id,
        inspectionId: cmd.inspectionId,
        format: cmd.format,
        requestedBy: cmd.actorUserId ? cmd.actorUserId : undefined,
      });

      await tx.insert(auditEvents).values({
        action: "report.requested",
        actorUserId: cmd.actorUserId,
        resourceType: "report",
        resourceId: cmd.id,
        requestId: cmd.requestId,
        ipAddress: cmd.ipAddress,
        metadata: { inspectionId: cmd.inspectionId, format: cmd.format },
      });
    });
    return (await this.findById(cmd.id))!;
  }

  async markGenerating(id: string): Promise<void> {
    await this.db.update(reportsTable).set({ status: "generating" }).where(eq(reportsTable.id, id));
  }

  async generateWithArtifact(cmd: GenerateReportWrite): Promise<Report> {
    await this.db.transaction(async (tx) => {
      await tx
        .update(reportsTable)
        .set({
          status: "ready",
          artifact: cmd.artifact,
          generatedBy: cmd.generatedBy ?? null,
          generatedAt: new Date(),
          error: null,
        })
        .where(eq(reportsTable.id, cmd.reportId));

      await tx.insert(auditEvents).values({
        action: "report.generated",
        actorUserId: cmd.actorUserId,
        resourceType: "report",
        resourceId: cmd.reportId,
        requestId: cmd.requestId,
        ipAddress: cmd.ipAddress,
      });

      await tx.insert(outboxEvents).values({
        type: cmd.eventType,
        correlationId: cmd.reportId,
        actorUserId: cmd.actorUserId,
        resourceType: "report",
        resourceId: cmd.reportId,
        payload: { reportId: cmd.reportId, status: "ready" },
      });
    });
    return (await this.findById(cmd.reportId))!;
  }

  async markFailed(cmd: FailReportWrite): Promise<void> {
    await this.db.transaction(async (tx) => {
      await tx
        .update(reportsTable)
        .set({ status: "failed", error: cmd.errorMessage.slice(0, 4000) })
        .where(eq(reportsTable.id, cmd.reportId));

      await tx.insert(auditEvents).values({
        action: "report.failed",
        actorUserId: cmd.actorUserId,
        resourceType: "report",
        resourceId: cmd.reportId,
        requestId: cmd.requestId,
        ipAddress: cmd.ipAddress,
        metadata: { error: cmd.errorMessage.slice(0, 4000) },
      });
    });
  }

  async finalize(cmd: FinalizeReportWrite): Promise<Report> {
    await this.db.transaction(async (tx) => {
      await tx
        .update(reportsTable)
        .set({
          status: "finalized",
          finalizedBy: cmd.finalizedBy,
          finalizedAt: new Date(),
        })
        .where(eq(reportsTable.id, cmd.reportId));

      await tx.insert(auditEvents).values({
        action: "report.finalized",
        actorUserId: cmd.actorUserId,
        resourceType: "report",
        resourceId: cmd.reportId,
        requestId: cmd.requestId,
        ipAddress: cmd.ipAddress,
      });
    });
    return (await this.findById(cmd.reportId))!;
  }

  async loadSnapshot(inspectionId: string): Promise<ReportSnapshot> {
    const [inspectionRows, findingRows, observationRows, correctiveRows, evidenceRows] =
      await Promise.all([
        this.db
          .select({
            id: inspectionsTable.id,
            type: inspectionsTable.type,
            status: inspectionsTable.status,
            projectCode: projectsTable.code,
            projectName: projectsTable.name,
            districtId: projectsTable.districtId,
            scheduledStart: inspectionsTable.scheduledStart,
            startedAt: inspectionsTable.startedAt,
            submittedAt: inspectionsTable.submittedAt,
            createdAt: inspectionsTable.createdAt,
          })
          .from(inspectionsTable)
          .innerJoin(projectsTable, eq(inspectionsTable.projectId, projectsTable.id))
          .where(eq(inspectionsTable.id, inspectionId))
          .limit(1),
        this.db
          .select()
          .from(findingsTable)
          .where(eq(findingsTable.inspectionId, inspectionId))
          .orderBy(asc(findingsTable.createdAt)),
        this.db
          .select()
          .from(observationsTable)
          .where(eq(observationsTable.inspectionId, inspectionId))
          .orderBy(asc(observationsTable.createdAt)),
        this.db
          .select()
          .from(correctiveActionsTable)
          .where(eq(correctiveActionsTable.inspectionId, inspectionId))
          .orderBy(asc(correctiveActionsTable.createdAt)),
        this.db
          .select()
          .from(evidenceTable)
          .where(eq(evidenceTable.inspectionId, inspectionId))
          .orderBy(asc(evidenceTable.capturedAt)),
      ]);

    const inspection = inspectionRows[0];
    if (!inspection) throw new Error(`Inspection not found: ${inspectionId}`);

    return {
      inspectionId,
      inspection: {
        id: inspection.id,
        type: inspection.type,
        status: inspection.status,
        projectCode: inspection.projectCode,
        projectName: inspection.projectName,
        districtId: inspection.districtId,
        scheduledStart: inspection.scheduledStart ? inspection.scheduledStart.toISOString() : null,
        startedAt: inspection.startedAt ? inspection.startedAt.toISOString() : null,
        submittedAt: inspection.submittedAt ? inspection.submittedAt.toISOString() : null,
        createdAt: inspection.createdAt.toISOString(),
      },
      findings: findingRows.map((f) => ({
        id: f.id,
        severity: f.severity,
        description: f.description,
        remediation: f.remediation,
        status: f.status,
        createdAt: f.createdAt.toISOString(),
      })),
      observations: observationRows.map((o) => ({
        id: o.id,
        userId: o.userId,
        text: o.text,
        createdAt: o.createdAt.toISOString(),
      })),
      correctiveActions: correctiveRows.map((c) => ({
        id: c.id,
        findingId: c.findingId,
        status: c.status,
        deadline: c.deadline ? c.deadline.toISOString() : null,
        createdAt: c.createdAt.toISOString(),
      })),
      evidence: evidenceRows.map((e) => ({
        id: e.id,
        evidenceType: e.evidenceType,
        fileName: e.fileName,
        uploadState: e.uploadState,
        integrityState: e.integrityState,
        capturedAt: e.capturedAt.toISOString(),
      })),
    };
  }
}
