import { randomUUID } from "node:crypto";
import { AppError } from "../../../infrastructure/errors.js";
import type { AuthorizationService } from "../../authorization/application/authorization-service.js";
import type { RequestUserContext } from "../../../infrastructure/request-context.js";
import type { AttendanceRepository } from "@netram/data";
import type { ObjectStoragePort } from "../../../infrastructure/object-storage.js";
import type {
  AttendanceAnomaly,
  AttendanceAnomalyState,
  AttendanceCalculation,
  AttendanceConfig,
  AttendanceCorrection,
  AttendanceDrillDownRow,
  AttendanceExport,
  AttendanceOverviewItem,
  AttendanceSource,
  AttendanceSourceObservation,
  AuditAction,
  CoverageLevel,
  DeviceHealthStatus,
  DomainEventType,
} from "@netram/types";
import type {
  AttendanceProviderPort,
  ProviderDeviceEvent,
} from "./ports/attendance-provider-port.js";
import {
  ATTENDANCE_CALCULATION_VERSION,
  calculateAttendance,
  dedupKeyFor,
  eventEstablishesPresence,
  inWindow,
  normalizeEventType,
  operationalDayFor,
} from "../domain/attendance.js";
import {
  ATTENDANCE_DETECTOR_VERSION,
  detectAnomalies,
  evaluateAttendanceAnomalyTransition,
  groupWithinProximity,
  materialityExceeded,
} from "../domain/attendance-anomaly.js";

const MONITOR_READ = "attendance:monitor:read";
const ANOMALY_READ = "attendance:anomaly:read";
const ANOMALY_REVIEW = "attendance:anomaly:review";
const INDIVIDUAL_READ = "attendance:individual:read";
const EXPORT = "attendance:export";
const CORRECTION_CREATE = "attendance:correction:create";
const CORRECTION_APPROVE = "attendance:correction:approve";
const CONFIG_WRITE = "attendance:config:write";
const INGEST = "attendance:ingest";

/** Above this many rows an export is generated by a background job. */
const LARGE_EXPORT_THRESHOLD = 5000;

const DEFAULT_CONFIG: Omit<AttendanceConfig, "projectId" | "updatedAt"> = {
  dayStartTime: "05:00",
  thresholds: {
    crossSourceDiscrepancy: 0.15,
    historicalDeviation: 0.25,
    persistenceWindowDays: 5,
    materialityThreshold: 0.1,
  },
  baseline: { windowDays: 14, minObservations: 5 },
  retention: { rawTransactionsDays: 365, exportsHours: 24 },
};

export interface AttendanceExportJobQueuePort {
  enqueue(exportId: string): Promise<void>;
}

export interface AttendanceServiceDeps {
  authz: AuthorizationService;
  repo: AttendanceRepository;
  provider: AttendanceProviderPort;
  storage: ObjectStoragePort;
  exportJobs: AttendanceExportJobQueuePort;
}

export interface SyncDeviceResult {
  received: number;
  inserted: number;
  duplicates: number;
  unmatched: number;
  normalized: number;
  affectedWindows: Array<{ windowId: string; operationalDate: string }>;
}

interface AffectedKey {
  windowId: string;
  operationalDate: string;
}

export class AttendanceService {
  constructor(private readonly deps: AttendanceServiceDeps) {}

  private get authz(): AuthorizationService {
    return this.deps.authz;
  }

  private get repo(): AttendanceRepository {
    return this.deps.repo;
  }

  /* ---------- Authorization helpers ---------- */

  private async requireProjectScope(
    ctx: RequestUserContext,
    projectId: string,
    permission: string,
  ): Promise<string | null> {
    const districtId = await this.repo.projectDistrictId(projectId);
    this.authz.requirePermission(ctx, permission as never, { districtId });
    return districtId;
  }

  /* ---------- Reads: aggregate-first monitoring (§36) ---------- */

  async listOverview(
    ctx: RequestUserContext,
    query: {
      from?: string;
      to?: string;
      page?: number;
      pageSize?: number;
    },
  ): Promise<{ items: AttendanceOverviewItem[]; total: number; page: number; pageSize: number }> {
    this.authz.requirePermission(ctx, MONITOR_READ);
    const scope = this.authz.accessibleDistrictIds(ctx);
    const pageNum = query.page ?? 1;
    const pageSize = query.pageSize ?? 20;
    const page = await this.repo.listOverview({
      jurisdictionIds: scope ? [...scope] : undefined,
      from: query.from,
      to: query.to,
      page: pageNum,
      pageSize,
    });
    const openCounts = await this.repo.countOpenAnomaliesByProject({
      jurisdictionIds: scope ? [...scope] : undefined,
    });
    const countByProject = new Map(openCounts.map((r) => [r.projectId, r.count]));

    const items: AttendanceOverviewItem[] = page.items.map((c) => ({
      projectId: c.projectId,
      projectCode: c.projectCode,
      projectName: c.projectName,
      districtId: c.districtId,
      windowId: c.windowId,
      windowCode: "",
      operationalDate: c.operationalDate,
      expected: c.expected,
      present: c.present,
      coverage: c.coverage,
      dataQuality: c.dataQuality,
      openAnomalyCount: countByProject.get(c.projectId) ?? 0,
      latestComputedAt: c.computedAt,
      sourceCounts: c.sourceCounts,
    }));
    return { items, total: page.total, page: pageNum, pageSize };
  }

  async listCalculations(
    ctx: RequestUserContext,
    query: {
      projectId?: string;
      windowId?: string;
      from?: string;
      to?: string;
      page?: number;
      pageSize?: number;
    },
  ): Promise<{ items: AttendanceCalculation[]; total: number; page: number; pageSize: number }> {
    this.authz.requirePermission(ctx, MONITOR_READ);
    const scope = this.authz.accessibleDistrictIds(ctx);
    const pageNum = query.page ?? 1;
    const pageSize = query.pageSize ?? 20;
    const page = await this.repo.listCalculations({
      projectId: query.projectId,
      windowId: query.windowId,
      from: query.from,
      to: query.to,
      jurisdictionIds: scope ? [...scope] : undefined,
      page: pageNum,
      pageSize,
    });
    return { items: page.items, total: page.total, page: pageNum, pageSize };
  }

  async listDevices(ctx: RequestUserContext, projectId?: string) {
    this.authz.requirePermission(ctx, MONITOR_READ);
    if (projectId) await this.requireProjectScope(ctx, projectId, MONITOR_READ);
    const scope = this.authz.accessibleDistrictIds(ctx);
    const devices = await this.repo.listDevices({
      projectId,
      jurisdictionIds: scope ? [...scope] : undefined,
    });
    return devices.map((d) => ({
      id: d.id,
      projectId: d.projectId,
      projectCode: d.projectCode,
      projectName: d.projectName,
      name: d.name,
      status: d.status,
      lastSeenAt: d.lastSeenAt,
      lastEventAt: d.lastEventAt,
      stale:
        d.status !== "UNKNOWN" &&
        (!d.lastSeenAt || Date.now() - new Date(d.lastSeenAt).getTime() > 24 * 3_600_000),
    }));
  }

  async listWindows(ctx: RequestUserContext, projectId: string) {
    this.authz.requirePermission(ctx, MONITOR_READ);
    await this.requireProjectScope(ctx, projectId, MONITOR_READ);
    return this.repo.listWindows(projectId);
  }

  async listSourceObservations(
    ctx: RequestUserContext,
    projectId: string,
    from?: string,
    to?: string,
  ): Promise<AttendanceSourceObservation[]> {
    this.authz.requirePermission(ctx, MONITOR_READ);
    await this.requireProjectScope(ctx, projectId, MONITOR_READ);
    return this.repo.listSourceObservations({ projectId, from, to });
  }

  async listIdentityMappings(
    ctx: RequestUserContext,
    projectId: string,
    page = 1,
    pageSize = 20,
  ) {
    this.authz.requirePermission(ctx, MONITOR_READ);
    await this.requireProjectScope(ctx, projectId, MONITOR_READ);
    return this.repo.listIdentityMappings({ projectId, page, pageSize });
  }

  /* ---------- Anomaly reads & review (§30, §31) ---------- */

  async listAnomalies(
    ctx: RequestUserContext,
    query: {
      projectId?: string;
      type?: string;
      severity?: string;
      state?: string;
      from?: string;
      to?: string;
      page?: number;
      pageSize?: number;
    },
  ): Promise<{
    items: AttendanceAnomaly[];
    total: number;
    page: number;
    pageSize: number;
  }> {
    this.authz.requirePermission(ctx, ANOMALY_READ);
    const scope = this.authz.accessibleDistrictIds(ctx);
    const pageNum = query.page ?? 1;
    const pageSize = query.pageSize ?? 20;
    const page = await this.repo.listAnomalies({
      projectId: query.projectId,
      type: query.type,
      severity: query.severity,
      state: query.state,
      from: query.from,
      to: query.to,
      jurisdictionIds: scope ? [...scope] : undefined,
      page: pageNum,
      pageSize,
    });
    return { items: page.items, total: page.total, page: pageNum, pageSize };
  }

  async getAnomaly(ctx: RequestUserContext, id: string): Promise<AttendanceAnomaly> {
    this.authz.requirePermission(ctx, ANOMALY_READ);
    const anomaly = await this.repo.findById(id);
    if (!anomaly) throw AppError.notFound("Attendance anomaly not found.");
    this.authz.requirePermission(ctx, ANOMALY_READ, { districtId: anomaly.districtId });
    return anomaly;
  }

  async listReviewActions(ctx: RequestUserContext, anomalyId: string) {
    const anomaly = await this.getAnomaly(ctx, anomalyId);
    this.authz.requirePermission(ctx, ANOMALY_READ, { districtId: anomaly.districtId });
    return this.repo.listReviewActions(anomalyId);
  }

  async reviewAnomaly(
    ctx: RequestUserContext,
    anomalyId: string,
    input: {
      action: "acknowledge" | "dismiss" | "false_positive" | "investigate" | "actioned" | "link_inspection" | "link_complaint" | "note";
      note?: string | null;
      linkedInspectionId?: string | null;
      linkedComplaintId?: string | null;
    },
  ): Promise<AttendanceAnomaly> {
    const anomaly = await this.repo.findById(anomalyId);
    if (!anomaly) throw AppError.notFound("Attendance anomaly not found.");
    this.authz.requirePermission(ctx, ANOMALY_REVIEW, { districtId: anomaly.districtId });

    const stateForAction: Partial<Record<typeof input.action, AttendanceAnomalyState>> = {
      acknowledge: "REVIEWED",
      dismiss: "DISMISSED",
      false_positive: "FALSE_POSITIVE",
      investigate: "INVESTIGATING",
      actioned: "ACTIONED",
    };

    const note = input.note ?? null;
    const reviewAction = input.action;
    const auditAction: AuditAction =
      input.action === "dismiss"
        ? "attendance.anomaly_dismissed"
        : input.action === "false_positive"
          ? "attendance.anomaly_false_positive"
          : input.action === "investigate"
            ? "attendance.anomaly_investigating"
            : input.action === "actioned"
              ? "attendance.anomaly_actioned"
              : "attendance.anomaly_reviewed";
    const eventType: DomainEventType =
      input.action === "dismiss"
        ? "attendance.anomaly_dismissed"
        : input.action === "false_positive"
          ? "attendance.anomaly_false_positive"
          : input.action === "investigate"
            ? "attendance.anomaly_investigating"
            : input.action === "actioned"
              ? "attendance.anomaly_actioned"
              : "attendance.anomaly_reviewed";

    const to = stateForAction[input.action] ?? anomaly.state;
    if (to !== anomaly.state) {
      evaluateAttendanceAnomalyTransition(anomaly.state, to);
    }

    const updated = await this.repo.transitionAnomaly({
      anomalyId,
      to,
      reviewedBy: ctx.userId,
      reviewedAt: new Date(),
      reviewNotes: note,
      linkedInspectionId: input.linkedInspectionId,
      linkedComplaintId: input.linkedComplaintId,
      groupId: anomaly.groupId,
      reviewAction: reviewAction as never,
      audit: {
        actorUserId: ctx.userId,
        requestId: ctx.requestId ?? null,
        ipAddress: ctx.ipAddress ?? null,
        auditAction,
        auditMetadata: {
          from: anomaly.state,
          to,
          action: input.action,
          note,
          anomalyType: anomaly.anomalyType,
        },
        resourceType: "attendance-anomaly",
        resourceId: anomalyId,
      },
      event: {
        type: eventType,
        correlationId: anomalyId,
        actorUserId: ctx.userId,
        resourceType: "attendance-anomaly",
        resourceId: anomalyId,
        payload: {
          anomalyId,
          from: anomaly.state,
          to,
          action: input.action,
          anomalyType: anomaly.anomalyType,
          severity: anomaly.severity,
        },
      },
    });

    // Close the persistent group when the anomaly reaches a terminal state.
    if (anomaly.groupId && ["DISMISSED", "FALSE_POSITIVE", "ACTIONED"].includes(to)) {
      await this.repo.updateGroupState(anomaly.groupId, to, new Date());
    }
    return updated;
  }

  /* ---------- Individual drill-down (§37) ---------- */

  async drillDown(
    ctx: RequestUserContext,
    query: {
      projectId: string;
      personExternalId: string;
      windowId?: string;
      operationalDate?: string;
      from?: string;
      to?: string;
    },
  ): Promise<AttendanceDrillDownRow[]> {
    this.authz.requirePermission(ctx, INDIVIDUAL_READ);
    await this.requireProjectScope(ctx, query.projectId, INDIVIDUAL_READ);

    const rows = await this.repo.listEventsForPerson(query.projectId, query.personExternalId, {
      windowId: query.windowId,
      operationalDate: query.operationalDate,
      from: query.from,
      to: query.to,
    });

    // Every authorized individual-level access is audited and emitted as a durable event (§37, §46).
    const accessId = randomUUID();
    await this.repo.recordAudit({
      actorUserId: ctx.userId,
      requestId: ctx.requestId ?? null,
      ipAddress: ctx.ipAddress ?? null,
      auditAction: "attendance.individual_accessed",
      auditMetadata: {
        projectId: query.projectId,
        windowId: query.windowId ?? null,
        operationalDate: query.operationalDate ?? null,
        personExternalId: query.personExternalId,
        eventCount: rows.length,
      },
      resourceType: "attendance_person",
      resourceId: query.personExternalId,
    });
    await this.repo.enqueueEvent({
      type: "attendance.individual_accessed",
      correlationId: accessId,
      actorUserId: ctx.userId,
      resourceType: "attendance_person",
      resourceId: query.personExternalId,
      payload: {
        projectId: query.projectId,
        personExternalId: query.personExternalId,
        windowId: query.windowId ?? null,
        operationalDate: query.operationalDate ?? null,
        eventCount: rows.length,
      },
    });

    return rows.map((r) => ({
      personExternalId: r.personExternalId,
      netramUserId: r.netramUserId,
      eventType: r.eventType as AttendanceDrillDownRow["eventType"],
      occurredAt: r.occurredAt.toISOString(),
      deviceName: r.deviceName,
      windowCode: r.windowCode,
    }));
  }

  /* ---------- Ingestion (§6, §9, §19) ---------- */

  async syncDevice(
    ctx: RequestUserContext,
    deviceId: string,
    opts: { cursor?: string | null; operationalDate?: string },
  ): Promise<SyncDeviceResult & { deviceId: string; provider: string }> {
    this.authz.requirePermission(ctx, INGEST);
    const device = await this.repo.findDeviceById(deviceId);
    if (!device) throw AppError.notFound("Attendance device not found.");
    await this.requireProjectScope(ctx, device.projectId, INGEST);

    const cursor = opts.cursor ?? device.syncCursor;
    const events = opts.operationalDate
      ? await this.generateForDate(deviceId, opts.operationalDate, opts.cursor)
      : await this.deps.provider.sync(device, cursor);

    const result = await this.processDeviceEvents(device, events, ctx);

    const latestEventAt = events.reduce(
      (max, e) => (e.occurredAt.getTime() > max.getTime() ? e.occurredAt : max),
      new Date(0),
    );
    await this.repo.updateDeviceHealth(device.id, {
      status: "ONLINE",
      lastSeenAt: new Date(),
      lastEventAt: latestEventAt.getTime() > 0 ? latestEventAt : undefined,
      syncCursor: opts.cursor ?? device.syncCursor,
    });

    for (const key of result.affectedWindows) {
      await this.calculateWindow(ctx, key.windowId, key.operationalDate);
    }
    return { ...result, deviceId: device.id, provider: this.deps.provider.name };
  }

  /** Explicit provider events (used by tests and the demo ingest endpoint). */
  async ingestProviderEvents(
    ctx: RequestUserContext,
    deviceId: string,
    events: ProviderDeviceEvent[],
  ): Promise<SyncDeviceResult & { deviceId: string }> {
    this.authz.requirePermission(ctx, INGEST);
    const device = await this.repo.findDeviceById(deviceId);
    if (!device) throw AppError.notFound("Attendance device not found.");
    await this.requireProjectScope(ctx, device.projectId, INGEST);

    const result = await this.processDeviceEvents(device, events, ctx);
    const latestEventAt = events.reduce(
      (max, e) => (e.occurredAt.getTime() > max.getTime() ? e.occurredAt : max),
      new Date(0),
    );
    await this.repo.updateDeviceHealth(device.id, {
      status: "ONLINE",
      lastSeenAt: new Date(),
      lastEventAt: latestEventAt.getTime() > 0 ? latestEventAt : undefined,
    });
    for (const key of result.affectedWindows) {
      await this.calculateWindow(ctx, key.windowId, key.operationalDate);
    }
    return { ...result, deviceId: device.id };
  }

  private async generateForDate(
    deviceId: string,
    operationalDate: string,
    cursor?: string | null,
  ): Promise<ProviderDeviceEvent[]> {
    const device = await this.repo.findDeviceById(deviceId);
    if (!device) throw AppError.notFound("Attendance device not found.");
    const provider = this.deps.provider as unknown as {
      generate: (
        device: { id: string; projectId: string; deviceExternalId: string; config?: unknown },
        opts: { scenario?: string; operationalDate: string },
      ) => ProviderDeviceEvent[];
    };
    return provider.generate(device as unknown as Parameters<typeof provider.generate>[0], { operationalDate, scenario: cursor ?? undefined });
  }

  private async processDeviceEvents(
    device: { id: string; projectId: string },
    events: ProviderDeviceEvent[],
    ctx: RequestUserContext,
  ): Promise<SyncDeviceResult & { affectedWindows: AffectedKey[] }> {
    const windows = await this.repo.listWindows(device.projectId);
    const config = (await this.repo.getConfig(device.projectId)) ?? { ...DEFAULT_CONFIG, projectId: device.projectId, updatedAt: new Date().toISOString() };
    const affected = new Map<string, AffectedKey>();

    const rawWrites = events.map((e) => ({
      deviceId: device.id,
      externalUserId: e.externalUserId,
      deviceEventId: e.deviceEventId,
      occurredAt: e.occurredAt,
      rawType: e.rawType,
      payload: e.payload,
      syncCursor: null,
    }));

    const inserted = await this.repo.insertRawTransactions(rawWrites);
    const duplicates = events.length - inserted.length;

    let unmatched = 0;
    let normalized = 0;

    for (const raw of inserted) {
      const mapping = await this.repo.findIdentityMapping(device.id, raw.externalUserId);
      if (!mapping) {
        await this.repo.updateRawTransaction(raw.id, {
          status: "UNMATCHED",
          mappingStatus: "unmatched",
        });
        unmatched += 1;
        continue;
      }

      const window = windows.find((w) => inWindow(new Date(raw.occurredAt), w.startTime, w.endTime)) ?? null;
      const opDate = operationalDayFor(new Date(raw.occurredAt), config.dayStartTime);
      const eventType = normalizeEventType(raw.rawType);

      await this.repo.insertEvents([
        {
          id: randomUUID(),
          projectId: device.projectId,
          deviceId: device.id,
          populationId: window?.populationId ?? null,
          personExternalId: mapping.personExternalId,
          netramUserId: mapping.netramUserId,
          eventType,
          occurredAt: new Date(raw.occurredAt),
          rawTransactionId: raw.id,
          windowId: window?.id ?? null,
          operationalDate: opDate,
          dedupKey: window ? dedupKeyFor(device.projectId, window.id, opDate, mapping.personExternalId) : null,
        },
      ]);
      await this.repo.updateRawTransaction(raw.id, {
        status: "NORMALIZED",
        mappingStatus: null,
      });
      normalized += 1;

      if (window) {
        const key = `${window.id}:${opDate}`;
        affected.set(key, { windowId: window.id, operationalDate: opDate });
      }
    }

    // Audit + durable event for the ingestion batch (§45, §46).
    await this.repo.recordAudit({
      actorUserId: ctx.userId,
      requestId: ctx.requestId ?? null,
      ipAddress: ctx.ipAddress ?? null,
      auditAction: "attendance.device_synced",
      auditMetadata: {
        deviceId: device.id,
        projectId: device.projectId,
        received: events.length,
        inserted: inserted.length,
        duplicates,
        unmatched,
        normalized,
      },
      resourceType: "attendance-device",
      resourceId: device.id,
    });
    await this.repo.enqueueEvent({
      type: "attendance.event_received",
      correlationId: device.id,
      actorUserId: ctx.userId,
      resourceType: "attendance-device",
      resourceId: device.id,
      payload: {
        deviceId: device.id,
        projectId: device.projectId,
        received: events.length,
        inserted: inserted.length,
        duplicates,
        unmatched,
      },
    });
    if (normalized > 0) {
      await this.repo.enqueueEvent({
        type: "attendance.event_normalized",
        correlationId: device.id,
        actorUserId: ctx.userId,
        resourceType: "attendance-device",
        resourceId: device.id,
        payload: { deviceId: device.id, projectId: device.projectId, normalized },
      });
    }    return {
      received: events.length,
      inserted: inserted.length,
      duplicates,
      unmatched,
      normalized,
      affectedWindows: [...affected.values()],
    };
  }

  /* ---------- Source observations (§4, §22) ---------- */

  async recordSourceObservation(
    ctx: RequestUserContext,
    input: {
      projectId: string;
      source: AttendanceSource;
      windowId?: string | null;
      operationalDate: string;
      observedAt: string;
      observedCount?: number | null;
      expectedCount?: number | null;
      confidence?: number | null;
      coverage?: CoverageLevel;
      health?: DeviceHealthStatus;
      note?: string | null;
    },
  ): Promise<AttendanceSourceObservation> {
    this.authz.requirePermission(ctx, MONITOR_READ);
    if (input.source === "BIOMETRIC") {
      throw AppError.badRequest("Biometric observations are produced by device ingestion only.");
    }
    const window = input.windowId ? await this.repo.findWindowById(input.windowId) : null;
    if (input.windowId && !window) throw AppError.notFound("Attendance window not found.");
    if (window && window.projectId !== input.projectId) {
      throw AppError.badRequest("Window does not belong to the project.");
    }
    await this.requireProjectScope(ctx, input.projectId, MONITOR_READ);

    const observation = await this.repo.insertSourceObservation({
      id: randomUUID(),
      projectId: input.projectId,
      source: input.source,
      windowId: input.windowId ?? null,
      operationalDate: input.operationalDate,
      observedAt: new Date(input.observedAt),
      observedCount: input.observedCount ?? null,
      expectedCount: input.expectedCount ?? null,
      confidence: input.confidence ?? null,
      coverage: input.coverage ?? "COMPLETE",
      health: input.health ?? "ONLINE",
      note: input.note ?? null,
    });

    await this.repo.recordAudit({
      actorUserId: ctx.userId,
      requestId: ctx.requestId ?? null,
      ipAddress: ctx.ipAddress ?? null,
      auditAction: "attendance.observation_recorded",
      auditMetadata: { source: input.source, operationalDate: input.operationalDate, observedCount: input.observedCount ?? null },
      resourceType: "attendance-observation",
      resourceId: observation.id,
    });

    // An observation can complete a previously partial window — recalculate.
    if (window) {
      await this.calculateWindow(ctx, window.id, input.operationalDate);
    }
    return observation;
  }

  /* ---------- Calculation (§13, §23) ---------- */

  async calculateWindow(
    ctx: RequestUserContext,
    windowId: string,
    operationalDate: string,
  ): Promise<AttendanceCalculation> {
    const window = await this.repo.findWindowById(windowId);
    if (!window) throw AppError.notFound("Attendance window not found.");
    const config = (await this.repo.getConfig(window.projectId)) ?? { ...DEFAULT_CONFIG, projectId: window.projectId, updatedAt: new Date().toISOString() };

    // Expected population frozen at window start (§13).
    let expected: number | null = null;
    let expectedStrategy = "CONFIGURED";
    let populationId: string | null = window.populationId;
    if (window.populationId) {
      const populations = await this.repo.listPopulations(window.projectId);
      const population = populations.find((p) => p.id === window.populationId);
      if (population) {
        expectedStrategy = population.expectedStrategy;
        if (population.expectedStrategy === "ROSTER") {
          const members = await this.repo.listPopulationMembers(population.id);
          expected = members.length;
        } else {
          expected = population.expectedCount ?? null;
        }
      } else {
        populationId = null;
      }
    }

    const bounds = localWindowBounds(operationalDate, window.startTime, window.endTime);

    const events = await this.repo.listEventsForCalculation(
      window.projectId,
      windowId,
      operationalDate,
    );
    const unique = new Map<string, (typeof events)[number]>();
    for (const e of events) {
      if (!eventEstablishesPresence(e.eventType as never)) continue;
      if (!unique.has(e.dedupKey ?? e.id)) unique.set(e.dedupKey ?? e.id, e);
    }
    const presentEvents = [...unique.values()];

    const devices = await this.repo.listDevices({ projectId: window.projectId });
    const deviceCoverage: CoverageLevel =
      devices.length === 0
        ? "UNAVAILABLE"
        : devices.every((d) => d.lastEventAt && new Date(d.lastEventAt).getTime() >= bounds.start.getTime() - 30 * 60_000)
          ? "COMPLETE"
          : devices.some((d) => d.lastEventAt && new Date(d.lastEventAt).getTime() >= bounds.start.getTime())
            ? "PARTIAL"
            : "INSUFFICIENT";

    const reported = await this.repo.findSourceObservation(
      window.projectId,
      "INSTITUTION_REPORTED",
      windowId,
      operationalDate,
    );
    const cctv = await this.repo.findSourceObservation(
      window.projectId,
      "CCTV",
      windowId,
      operationalDate,
    );

    const sourceCoverage = [
      { source: "BIOMETRIC" as const, coverage: deviceCoverage },
      { source: "INSTITUTION_REPORTED" as const, coverage: reported ? reported.coverage : ("UNAVAILABLE" as CoverageLevel) },
      { source: "CCTV" as const, coverage: cctv ? cctv.coverage : ("UNAVAILABLE" as CoverageLevel) },
    ];

    const sourceCounts: Record<AttendanceSource, number> = {
      BIOMETRIC: presentEvents.length,
      INSTITUTION_REPORTED: reported?.observedCount ?? 0,
      CCTV: cctv?.observedCount ?? 0,
      MANUAL: 0,
    };

    const freshness = events.reduce((max, e) => {
      const t = e.receivedAt.getTime();
      return t > max ? t : max;
    }, reported ? new Date(reported.observedAt).getTime() : 0);
    const freshnessDate = freshness > 0 ? new Date(freshness) : null;
    const stale = !freshnessDate || Date.now() - freshnessDate.getTime() > 24 * 3_600_000;

    const dqRecord = await this.repo.findLatestDataQuality(
      window.projectId,
      "BIOMETRIC",
      bounds.start,
      bounds.end,
    );
    const duplicateRate = dqRecord?.duplicateRate ?? null;
    const unmatchedCount = dqRecord?.unmatchedCount ?? 0;

    const result = calculateAttendance({
      window,
      expected,
      presentEvents: presentEvents as never,
      sourceCounts,
      sourceCoverage,
      freshness: freshnessDate,
      duplicateRate,
      unmatchedCount,
      invalidCount: 0,
      stale,
      policy: {
        calculationVersion: ATTENDANCE_CALCULATION_VERSION,
        expectedStrategy,
        dayStartTime: config.dayStartTime,
        minCoverage: window.minCoverage,
        expectedFrozenAt: operationalDate,
      },
    });

    const calculation = await this.repo.upsertCalculation({
      projectId: window.projectId,
      windowId,
      operationalDate,
      expected: result.expected,
      present: result.present,
      absent: result.absent,
      unknown: result.unknown,
      sourceCounts: result.sourceCounts as Record<string, number>,
      coverage: result.coverage,
      dataQuality: result.dataQuality,
      freshness: result.freshness ?? null,
      policy: result.policy,
    });

    await this.repo.recordAudit({
      actorUserId: ctx.userId,
      requestId: ctx.requestId ?? null,
      ipAddress: ctx.ipAddress ?? null,
      auditAction: "attendance.calculation_computed",
      auditMetadata: {
        projectId: window.projectId,
        windowId,
        operationalDate,
        expected: result.expected,
        present: result.present,
        coverage: result.coverage,
        dataQuality: result.dataQuality,
      },
      resourceType: "attendance-calculation",
      resourceId: calculation.id,
    });
    await this.repo.enqueueEvent({
      type: "attendance.window_calculated",
      correlationId: calculation.id,
      actorUserId: ctx.userId,
      resourceType: "attendance-calculation",
      resourceId: calculation.id,
      payload: {
        projectId: window.projectId,
        windowId,
        operationalDate,
        expected: result.expected,
        present: result.present,
        coverage: result.coverage,
      },
    });

    await this.detectAndPersistAnomalies(ctx, window.projectId, populationId, windowId, operationalDate, bounds, config, result);

    return calculation;
  }

  /* ---------- Anomaly detection & persistence (§26-§34) ---------- */

  private async detectAndPersistAnomalies(
    ctx: RequestUserContext,
    projectId: string,
    populationId: string | null,
    windowId: string,
    operationalDate: string,
    bounds: { start: Date; end: Date },
    config: AttendanceConfig,
    result: Awaited<ReturnType<typeof calculateAttendance>>,
  ): Promise<void> {
    const history = await this.repo.listHistoricalPresent(
      projectId,
      windowId,
      daysBefore(operationalDate, config.baseline.windowDays),
      daysBefore(operationalDate, 0),
    );
    const prior = history.filter((h) => h.operationalDate < operationalDate);

    const candidates = detectAnomalies({
      present: result.present,
      expected: result.expected,
      history: prior.map((h) => h.present),
      biometricCount: result.sourceCounts.BIOMETRIC ?? null,
      reportedCount: result.sourceCounts.INSTITUTION_REPORTED || null,
      cctvCount: result.sourceCounts.CCTV || null,
      coverage: result.coverage,
      dataQuality: result.dataQuality,
      config,
    });

    for (const cand of candidates) {
      await this.persistAnomaly(ctx, {
        projectId,
        populationId,
        windowId,
        operationalDate,
        bounds,
        config,
        candidate: cand,
        present: result.present,
      });
    }
  }

  private async persistAnomaly(
    ctx: RequestUserContext,
    input: {
      projectId: string;
      populationId: string | null;
      windowId: string;
      operationalDate: string;
      bounds: { start: Date; end: Date };
      config: AttendanceConfig;
      candidate: { anomalyType: string; score: number; severity: string; confidence: number; supportingSignals: Record<string, unknown> };
      present: number;
    },
  ): Promise<void> {
    const { candidate } = input;
    const anomalyType = candidate.anomalyType as never;
    const existing = await this.repo.findOpenAnomalyFor(
      input.projectId,
      input.windowId,
      input.operationalDate,
      anomalyType,
    );

    const sourceData = {
      present: input.present,
      expected: null,
      windowId: input.windowId,
      operationalDate: input.operationalDate,
      detectorVersion: ATTENDANCE_DETECTOR_VERSION,
      computedAt: new Date().toISOString(),
    };

    if (existing) {
      if (existing.state === "NEW") {
        // Unreviewed: recalculate in place (§33).
        await this.repo.recalculateAnomaly({
          anomalyId: existing.id,
          score: candidate.score,
          severity: candidate.severity as never,
          confidence: candidate.confidence,
          dataQuality: existing.dataQuality,
          supportingSignals: candidate.supportingSignals,
          sourceData,
          observationEnd: input.bounds.end,
          audit: {
            actorUserId: ctx.userId,
            requestId: ctx.requestId ?? null,
            ipAddress: ctx.ipAddress ?? null,
            auditAction: "attendance.anomaly_updated",
            auditMetadata: { anomalyType, score: candidate.score, windowId: input.windowId, operationalDate: input.operationalDate },
            resourceType: "attendance-anomaly",
            resourceId: existing.id,
          },
          event: {
            type: "attendance.anomaly_updated",
            correlationId: existing.id,
            actorUserId: ctx.userId,
            resourceType: "attendance-anomaly",
            resourceId: existing.id,
            payload: { anomalyId: existing.id, anomalyType, score: candidate.score, severity: candidate.severity },
          },
        });
        return;
      }
      // Reviewed: only a materially different result creates a linked anomaly (§33).
      if (!materialityExceeded(existing.score, candidate.score, input.config.thresholds.materialityThreshold)) {
        return;
      }
    }

    const group = await this.findOrCreateGroup(
      input.projectId,
      input.populationId,
      anomalyType,
      input.config,
    );

    await this.repo.insertAnomaly({
      id: randomUUID(),
      projectId: input.projectId,
      populationId: input.populationId,
      windowId: input.windowId,
      operationalDate: input.operationalDate,
      observationStart: input.bounds.start,
      observationEnd: input.bounds.end,
      anomalyType,
      score: candidate.score,
      severity: candidate.severity as never,
      confidence: candidate.confidence,
      dataQuality: "UNKNOWN",
      detectorVersion: ATTENDANCE_DETECTOR_VERSION,
      supportingSignals: candidate.supportingSignals,
      sourceData: {
        ...sourceData,
        ...(existing ? { supersedes: existing.id } : {}),
      },
      groupId: group.id,
    });

    const anomalyId = (await this.repo.findOpenAnomalyFor(input.projectId, input.windowId, input.operationalDate, anomalyType))?.id;
    await this.repo.recordAudit({
      actorUserId: ctx.userId,
      requestId: ctx.requestId ?? null,
      ipAddress: ctx.ipAddress ?? null,
      auditAction: "attendance.anomaly_detected",
      auditMetadata: {
        projectId: input.projectId,
        windowId: input.windowId,
        operationalDate: input.operationalDate,
        anomalyType,
        score: candidate.score,
        severity: candidate.severity,
        supersedes: existing?.id ?? null,
      },
      resourceType: "attendance-anomaly",
      resourceId: anomalyId ?? "",
    });
    await this.repo.enqueueEvent({
      type: "attendance.anomaly_detected",
      correlationId: anomalyId ?? group.id,
      actorUserId: ctx.userId,
      resourceType: "attendance-anomaly",
      resourceId: anomalyId ?? group.id,
      payload: {
        projectId: input.projectId,
        windowId: input.windowId,
        operationalDate: input.operationalDate,
        anomalyType,
        score: candidate.score,
        severity: candidate.severity,
        confidence: candidate.confidence,
      },
    });
  }

  private async findOrCreateGroup(
    projectId: string,
    populationId: string | null,
    anomalyType: never,
    _config: AttendanceConfig,
  ) {
    const open = await this.repo.findOpenGroup(projectId, populationId, anomalyType);
    if (open && groupWithinProximity(new Date(open.openedAt), new Date(), 7)) {
      return open;
    }
    return this.repo.createGroup({
      id: randomUUID(),
      projectId,
      populationId,
      anomalyType,
    });
  }

  /* ---------- Configuration (§43) ---------- */

  async getConfig(ctx: RequestUserContext, projectId?: string): Promise<AttendanceConfig> {
    this.authz.requirePermission(ctx, MONITOR_READ);
    if (projectId) await this.requireProjectScope(ctx, projectId, MONITOR_READ);
    return (await this.repo.getConfig(projectId ?? null)) ?? { projectId: projectId ?? null, ...DEFAULT_CONFIG, updatedAt: new Date().toISOString() };
  }

  async updateConfig(
    ctx: RequestUserContext,
    projectId: string | null,
    input: {
      dayStartTime?: string;
      thresholds?: Partial<AttendanceConfig["thresholds"]>;
      baseline?: Partial<AttendanceConfig["baseline"]>;
      retention?: Partial<AttendanceConfig["retention"]>;
    },
  ): Promise<AttendanceConfig> {
    this.authz.requirePermission(ctx, CONFIG_WRITE);
    if (projectId) await this.requireProjectScope(ctx, projectId, CONFIG_WRITE);

    const existing = (await this.repo.getConfig(projectId)) ?? {
      projectId,
      ...DEFAULT_CONFIG,
      updatedAt: new Date().toISOString(),
    };
    const updated = {
      projectId,
      dayStartTime: input.dayStartTime ?? existing.dayStartTime,
      thresholds: { ...existing.thresholds, ...input.thresholds },
      baseline: { ...existing.baseline, ...input.baseline },
      retention: { ...existing.retention, ...input.retention },
    };
    const saved = await this.repo.upsertConfig({
      projectId: updated.projectId,
      dayStartTime: updated.dayStartTime,
      thresholds: updated.thresholds,
      baseline: updated.baseline,
      retention: updated.retention,
    });

    await this.repo.recordAudit({
      actorUserId: ctx.userId,
      requestId: ctx.requestId ?? null,
      ipAddress: ctx.ipAddress ?? null,
      auditAction: "attendance.config_changed",
      auditMetadata: {
        projectId,
        dayStartTime: input.dayStartTime ?? null,
        thresholds: input.thresholds ?? null,
        baseline: input.baseline ?? null,
        retention: input.retention ?? null,
      },
      resourceType: "attendance-config",
      resourceId: projectId ?? "programme-default",
    });
    return saved;
  }

  /* ---------- Corrections (§34) ---------- */

  async createCorrection(
    ctx: RequestUserContext,
    input: {
      projectId: string;
      targetType: "calculation" | "anomaly" | "event";
      targetId: string;
      field: string;
      newValue: Record<string, unknown>;
      reason: string;
    },
  ): Promise<AttendanceCorrection> {
    this.authz.requirePermission(ctx, CORRECTION_CREATE);
    await this.requireProjectScope(ctx, input.projectId, CORRECTION_CREATE);

    let originalValue: Record<string, unknown>;
    if (input.targetType === "calculation") {
      const calc = await this.repo.findCalculationById(input.targetId);
      if (!calc) throw AppError.notFound("Attendance calculation not found.");
      originalValue = { present: calc.present, expected: calc.expected };
    } else if (input.targetType === "anomaly") {
      const anomaly = await this.repo.findById(input.targetId);
      if (!anomaly) throw AppError.notFound("Attendance anomaly not found.");
      originalValue = { state: anomaly.state, score: anomaly.score };
    } else {
      const event = await this.repo.findEventById(input.targetId);
      if (!event) throw AppError.notFound("Attendance event not found.");
      originalValue = { eventType: event.eventType, occurredAt: event.occurredAt };
    }

    const correction = await this.repo.insertCorrection({
      id: randomUUID(),
      projectId: input.projectId,
      targetType: input.targetType,
      targetId: input.targetId,
      field: input.field,
      originalValue,
      newValue: input.newValue,
      reason: input.reason,
      requestedBy: ctx.userId,
    });

    await this.repo.recordAudit({
      actorUserId: ctx.userId,
      requestId: ctx.requestId ?? null,
      ipAddress: ctx.ipAddress ?? null,
      auditAction: "attendance.correction_created",
      auditMetadata: {
        projectId: input.projectId,
        targetType: input.targetType,
        targetId: input.targetId,
        field: input.field,
      },
      resourceType: "attendance-correction",
      resourceId: correction.id,
    });
    await this.repo.enqueueEvent({
      type: "attendance.correction_created",
      correlationId: correction.id,
      actorUserId: ctx.userId,
      resourceType: "attendance-correction",
      resourceId: correction.id,
      payload: { correctionId: correction.id, projectId: input.projectId, targetType: input.targetType, targetId: input.targetId },
    });
    return correction;
  }

  async listCorrections(ctx: RequestUserContext, projectId: string) {
    this.authz.requirePermission(ctx, CORRECTION_CREATE);
    await this.requireProjectScope(ctx, projectId, CORRECTION_CREATE);
    return this.repo.listCorrections({ projectId });
  }

  async decideCorrection(
    ctx: RequestUserContext,
    correctionId: string,
    decision: "approve" | "reject",
  ): Promise<AttendanceCorrection> {
    this.authz.requirePermission(ctx, CORRECTION_APPROVE);
    const correction = await this.repo.findCorrectionById(correctionId);
    if (!correction) throw AppError.notFound("Attendance correction not found.");
    await this.requireProjectScope(ctx, correction.projectId, CORRECTION_APPROVE);

    if (correction.status !== "PENDING") {
      throw AppError.conflict(`Correction is already ${correction.status.toLowerCase()}.`);
    }
    // Independent approval: the requester cannot approve their own correction (§34).
    if (correction.requestedBy === ctx.userId) {
      throw AppError.forbidden("Approval must be made by a different authority than the requester.");
    }

    if (decision === "reject") {
      const rejected = await this.repo.updateCorrectionStatus(correctionId, "REJECTED", ctx.userId);
      await this.repo.recordAudit({
        actorUserId: ctx.userId,
        requestId: ctx.requestId ?? null,
        ipAddress: ctx.ipAddress ?? null,
        auditAction: "attendance.correction_rejected",
        auditMetadata: { correctionId, projectId: correction.projectId },
        resourceType: "attendance-correction",
        resourceId: correctionId,
      });
      return rejected!;
    }

    // Approve: apply the change to the target (calculation present today).
    if (correction.targetType === "calculation" && correction.field === "present") {
      const present = Number(correction.newValue.present);
      if (!Number.isInteger(present) || present < 0) {
        throw AppError.badRequest("newValue.present must be a non-negative integer.");
      }
      const calc = await this.repo.findCalculationById(correction.targetId);
      if (!calc) throw AppError.notFound("Attendance calculation not found.");
      const expected = calc.expected;
      const absent =
        expected !== null && calc.coverage === "COMPLETE" ? Math.max(0, expected - present) : null;
      const unknown =
        expected !== null ? Math.max(0, expected - present) : 0;
      await this.repo.updateCalculationDerived(correction.targetId, { present, absent, unknown });
    } else if (correction.targetType === "calculation") {
      throw AppError.badRequest("Only the calculation 'present' field is supported for correction.");
    } else {
      throw AppError.badRequest("Only calculation corrections are supported in this version.");
    }

    const approved = await this.repo.updateCorrectionStatus(correctionId, "APPROVED", ctx.userId);
    await this.repo.recordAudit({
      actorUserId: ctx.userId,
      requestId: ctx.requestId ?? null,
      ipAddress: ctx.ipAddress ?? null,
      auditAction: "attendance.correction_approved",
      auditMetadata: { correctionId, projectId: correction.projectId, targetId: correction.targetId, field: correction.field },
      resourceType: "attendance-correction",
      resourceId: correctionId,
    });
    await this.repo.enqueueEvent({
      type: "attendance.correction_approved",
      correlationId: correctionId,
      actorUserId: ctx.userId,
      resourceType: "attendance-correction",
      resourceId: correctionId,
      payload: { correctionId, projectId: correction.projectId },
    });
    return approved!;
  }

  /* ---------- Exports (§38-§41) ---------- */

  async requestExport(
    ctx: RequestUserContext,
    query: { projectId?: string; districtId?: string; from?: string; to?: string },
  ): Promise<{ export: AttendanceExport; csv?: string }> {
    this.authz.requirePermission(ctx, EXPORT);
    if (query.projectId) {
      await this.requireProjectScope(ctx, query.projectId, EXPORT);
    } else {
      // District-level export: caller must have export permission for the district.
      this.authz.requirePermission(ctx, EXPORT, { districtId: query.districtId ?? null });
    }
    const scope = this.authz.accessibleDistrictIds(ctx);

    const exportRecord = await this.repo.insertExport({
      id: randomUUID(),
      projectId: query.projectId ?? "",
      requestedBy: ctx.userId,
      scope: { projectId: query.projectId ?? null, districtId: query.districtId ?? null, from: query.from ?? null, to: query.to ?? null },
      format: "csv",
    });

    await this.repo.recordAudit({
      actorUserId: ctx.userId,
      requestId: ctx.requestId ?? null,
      ipAddress: ctx.ipAddress ?? null,
      auditAction: "attendance.export_requested",
      auditMetadata: { scope: exportRecord.scope },
      resourceType: "attendance-export",
      resourceId: exportRecord.id,
    });
    await this.repo.enqueueEvent({
      type: "attendance.export_requested",
      correlationId: exportRecord.id,
      actorUserId: ctx.userId,
      resourceType: "attendance-export",
      resourceId: exportRecord.id,
      payload: { exportId: exportRecord.id, projectId: exportRecord.projectId },
    });

    const rows = await this.repo.listAllCalculations({
      projectId: query.projectId,
      jurisdictionIds: scope ? [...scope] : undefined,
      from: query.from,
      to: query.to,
    });
    const csv = buildAttendanceCsv(rows);

    if (rows.length > LARGE_EXPORT_THRESHOLD) {
      // Large export → background job (§39).
      await this.repo.updateExport(exportRecord.id, { status: "GENERATING" });
      await this.deps.exportJobs.enqueue(exportRecord.id);
      return { export: (await this.repo.findExportById(exportRecord.id))! };
    }

    return this.finalizeExport(ctx, exportRecord.id, csv, rows.length);
  }

  async finalizeExport(
    ctx: RequestUserContext,
    exportId: string,
    csv: string,
    recordCount: number,
  ): Promise<{ export: AttendanceExport; csv: string }> {
    const config = (await this.repo.getConfig(null)) ?? { ...DEFAULT_CONFIG, projectId: null, updatedAt: new Date().toISOString() };
    const artifactKey = `attendance-exports/${exportId}.csv`;
    await this.deps.storage.put(artifactKey, Buffer.from(csv, "utf8"), "text/csv");
    const expiresAt = new Date(Date.now() + config.retention.exportsHours * 3_600_000);

    await this.repo.updateExport(exportId, {
      status: "READY",
      artifactKey,
      recordCount,
      generatedAt: new Date(),
      expiresAt,
      error: null,
    });
    await this.repo.recordAudit({
      actorUserId: ctx.userId,
      requestId: ctx.requestId ?? null,
      ipAddress: ctx.ipAddress ?? null,
      auditAction: "attendance.export_generated",
      auditMetadata: { exportId, recordCount },
      resourceType: "attendance-export",
      resourceId: exportId,
    });
    await this.repo.enqueueEvent({
      type: "attendance.export_completed",
      correlationId: exportId,
      actorUserId: ctx.userId,
      resourceType: "attendance-export",
      resourceId: exportId,
      payload: { exportId, recordCount },
    });
    return { export: (await this.repo.findExportById(exportId))!, csv };
  }

  async getExport(ctx: RequestUserContext, id: string): Promise<AttendanceExport> {
    this.authz.requirePermission(ctx, EXPORT);
    const record = await this.repo.findExportById(id);
    if (!record) throw AppError.notFound("Attendance export not found.");
    await this.requireProjectScope(ctx, record.projectId, EXPORT);
    return record;
  }

  async listExports(ctx: RequestUserContext, projectId: string): Promise<AttendanceExport[]> {
    this.authz.requirePermission(ctx, EXPORT);
    await this.requireProjectScope(ctx, projectId, EXPORT);
    return this.repo.listExports({ projectId });
  }

  async downloadExport(ctx: RequestUserContext, id: string): Promise<{ csv: Buffer; filename: string }> {
    this.authz.requirePermission(ctx, EXPORT);
    const record = await this.repo.findExportById(id);
    if (!record) throw AppError.notFound("Attendance export not found.");
    await this.requireProjectScope(ctx, record.projectId, EXPORT);

    if (record.status === "EXPIRED") {
      throw AppError.badRequest("Export artifact has expired (retention window elapsed).");
    }
    if (record.status !== "READY" || !record.artifactKey) {
      throw AppError.conflict(`Export is not ready (status=${record.status}).`);
    }
    const stream = await this.deps.storage.get(record.artifactKey);
    const chunks: Buffer[] = [];
    for await (const chunk of stream) chunks.push(chunk as Buffer);
    const csv = Buffer.concat(chunks);

    await this.repo.updateExport(id, { downloadedAt: new Date() });
    await this.repo.recordAudit({
      actorUserId: ctx.userId,
      requestId: ctx.requestId ?? null,
      ipAddress: ctx.ipAddress ?? null,
      auditAction: "attendance.export_downloaded",
      auditMetadata: { exportId: id, recordCount: record.recordCount },
      resourceType: "attendance-export",
      resourceId: id,
    });
    return { csv, filename: `netram-attendance-${id.slice(0, 8)}.csv` };
  }

  /** Idempotent export cleanup: expires READY exports past retention (§40). */
  async expireExports(): Promise<number> {
    const expired = await this.repo.expireExports(new Date());
    return expired;
  }
}

/* ---------- Helpers ---------- */

function localWindowBounds(opDate: string, startTime: string, endTime: string): { start: Date; end: Date } {
  const [sh, sm] = startTime.split(":").map(Number);
  const [eh, em] = endTime.split(":").map(Number);
  const start = new Date(`${opDate}T${startTime}:00.000Z`);
  let end = new Date(`${opDate}T${endTime}:00.000Z`);
  if (end.getTime() <= start.getTime()) {
    end = new Date(end.getTime() + 24 * 3_600_000);
  }
  void sh;
  void sm;
  void eh;
  void em;
  return { start, end };
}

function daysBefore(opDate: string, days: number): string {
  const d = new Date(`${opDate}T00:00:00.000Z`);
  d.setUTCDate(d.getUTCDate() - days);
  return d.toISOString().slice(0, 10);
}

export function buildAttendanceCsv(rows: AttendanceCalculation[]): string {
  const header = [
    "operationalDate",
    "projectId",
    "windowId",
    "expected",
    "present",
    "absent",
    "unknown",
    "sourceBiometric",
    "sourceReported",
    "sourceCctv",
    "coverage",
    "dataQuality",
    "computedAt",
  ];
  const lines = rows.map((r) =>
    [
      r.operationalDate,
      r.projectId,
      r.windowId,
      r.expected ?? "",
      r.present,
      r.absent ?? "",
      r.unknown,
      r.sourceCounts.BIOMETRIC ?? "",
      r.sourceCounts.INSTITUTION_REPORTED ?? "",
      r.sourceCounts.CCTV ?? "",
      r.coverage,
      r.dataQuality,
      r.computedAt,
    ]
      .map((v) => String(v).replace(/"/g, '""'))
      .map((v) => `"${v}"`)
      .join(","),
  );
  return [header.join(","), ...lines].join("\n");
}